apiVersion: v2
appVersion: v0.11.1
description: A ORY Kratos Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-kratos.svg
name: kratos
type: application
version: 0.29.0
