apiVersion: v2
appVersion: v0.2.8
dependencies:
- condition: deploy.kratos.enable
  name: kratos
  repository: https://k8s.ory.sh/helm/charts
  version: 0.29.0
- condition: deploy.elasticsearch.enable
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.17.1
- condition: deploy.postgresql.enable
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 11.1.9
- condition: deploy.filebeat.enable
  name: filebeat
  repository: https://helm.elastic.co
  version: 7.17.1
- condition: deploy.fluentbit.enable
  name: fluent-bit
  repository: https://fluent.github.io/helm-charts
  version: 0.20.8
- condition: deploy.contour.enable
  name: contour
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 7.8.0
description: A Helm chart for Paralus ZTKA.
maintainers:
- name: Paralus Team
name: ztka
type: application
version: 0.2.9
