alertmanager:
  enabled: false

server:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

serverFiles:
  alerting_rules.yml:
   groups:
     - name: Instances
       rules:
         - alert: InstanceDown
           expr: up == 0
           for: 5m
           labels:
             severity: page
           annotations:
             description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
             summary: 'Instance {{ $labels.instance }} down'
     - name: Pods
       rules:
         - alert: PodsDown
           expr: |
             kube_pod_status_phase{phase=~"Failed|Unknown"} > 0
           for: 5m
           labels:
             severity: critical
           annotations:
             summary: "Pod(s) down in {{ $labels.namespace }}"
             description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not running (state: {{ $labels.phase }}) for more than 5 minutes."
         - alert: ErrImagePull
           expr: |
             kube_pod_container_status_waiting_reason{reason=~"ErrImagePull|ImagePullBackOff"} > 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Pod Image Pull Error in {{ $labels.namespace }}"
             description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is failing to pull the container image for more than 5 minutes."