apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: cloudnative-pg
spec:
  instances: 1
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: "1"